MyPortfolio/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include(('Portfolio.urls','portfolio'),namespace='portfolio')),
    path('suraj-portfolio-administrator/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Portfolio/urls.py
from django.urls import path, re_path

from MyPortfolio import settings
from . import views
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    
    path('',views.home,name='home'),
    path('portfolio/project/<str:project_name>/',views.projectInfo,name="project"),
    path('download-resume',views.downloadResume,name='download-resume'),
]

Portfolio/models.py
from django.db import models

class Project(models.Model):

    CATEGORY_CHOICES = [
        ('Web Development', 'Web Development'),
        ('Desktop Application', 'Desktop Application'),
        ('Data Science', 'Data Science'),
        ('Android Application', 'Mobile App'),
        ('IOS Application', 'IOS Mobile App'),
    ]

    STATUS_CHOICES = [
        ('Ongoing', 'Ongoing'),
        ('Completed', 'Completed'),
        ('Pending', 'Pending'),
    ]


    project_name = models.CharField(max_length=100,unique=True)
    intro = models.TextField()
    project_description = models.TextField()
    category_type = models.CharField(max_length=50, choices=CATEGORY_CHOICES)
    stack = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    images = models.ImageField(upload_to='projects/', null=True, blank=True)  

    def __str__(self):
        return self.project_name


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, related_name='project_images', on_delete=models.CASCADE) 
    image = models.ImageField(upload_to='project/images/', verbose_name='Image')

    def __str__(self):
        return f"Image for {self.project.project_name}"

Portfolio/views.py
from pathlib import Path
from django.http import FileResponse, Http404
from django.shortcuts import redirect, render
from Portfolio.models import Project,ProjectImage


def home(request):
    try:
        project = Project.objects.all()
        print(project[0].images.url)
        return render(request,"index.html",{'project':project})
    except:
        return render(request,'index.html')


def projectInfo(request,project_name):
    try:
        project_info = Project.objects.get(project_name = project_name)
        project_images = ProjectImage.objects.filter(project = project_info)
        return render(request,"developed-details.html",{'project_info':project_info,'project_images':project_images})
    except:
        return render(request,'developed-details.html')

def downloadResume(request):
    try:
        import os
        from MyPortfolio import settings
        file_path = os.path.join(settings.MEDIA_ROOT,"Resume.pdf")
        if not os.path.exists(file_path):
            raise Http404("File Not Found")
        response = FileResponse(open(file_path,'rb'),content_type="application/pdf")
        response['Content-Disposition'] = f'attachment; filename="Suraj_Giri_Resume.pdf" '
        return response
    except:
        raise Http404("File Not Found")
        

Portfolio/templates/JSimport.html
 {% load static %}
 <!-- Vendor JS Files -->
 <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
 <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>
 <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
 <script src="{% static 'assets/vendor/typed.js/typed.umd.js' %}"></script>
 <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
 <script src="{% static 'assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
 <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
 <script src="{% static 'assets/vendor/imagesloaded/imagesloaded.pkgd.min.js' %}"></script>
 <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
 <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

 <!-- Main JS File -->
 <script src="{% static 'assets/js/main.js' %}"></script>

Portfolio/templates/developed-details.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>Portfolio Details</title>
  <meta name="description" content="Explore Suraj Giri's developer portfolio showcasing projects, skills, and achievements in web, application and software development.">
  <meta name="keywords" content="developer portfolio, Suraj Giri, surajgiri974, web developer, software developer, programming projects, coding portfolio, application developer, database">
  
  {% include 'imports.html' %}

  <style>
    @media (min-width:1000px) {
      img {
        height: 600px;     
        object-position: center;
        object-fit: contain;   
  }
    }
  </style>
</head>

<body class="portfolio-details-page">

  {% include 'navigation.html' %}

  <main class="main">

    <!-- Page Title -->
    <div class="page-title" data-aos="fade">
      <div class="container">
        <nav class="breadcrumbs">
          <ol>
            <li><a href="{% url 'portfolio:home' %}">Home</a></li>
            <li class="current">Portfolio Details</li>
          </ol>
        </nav>
        <h1>Portfolio Details</h1>
      </div>
    </div><!-- End Page Title -->

    <!-- Portfolio Details Section -->
    <section id="portfolio-details" class="portfolio-details section">

      <div class="container" data-aos="fade-up">

        <div class="portfolio-details-slider swiper init-swiper">
          <script type="application/json" class="swiper-config">
            {
              "loop": true,
              "speed": 600,
              "autoplay": {
                "delay": 5000
              },
              "slidesPerView": "auto",
              "navigation": {
                "nextEl": ".swiper-button-next",
                "prevEl": ".swiper-button-prev"
              },
              "pagination": {
                "el": ".swiper-pagination",
                "type": "bullets",
                "clickable": true
              }
            }
          </script>
          <div class="swiper-wrapper align-items-center">

          {% if project_images %}
            {% for i in project_images %}
              <div class="swiper-slide"> 
                <img src="{{ i.image.url }}" alt=""  />
              </div>
            {% endfor %}
          {% else %}
            <p>No images available for this project.</p>
          {% endif %}
          
          </div>
          <div class="swiper-button-prev"></div>
          <div class="swiper-button-next"></div>
          <div class="swiper-pagination"></div>
        </div>

        <div class="row justify-content-between gy-4 mt-4">

          <div class="col-lg-8" data-aos="fade-up">
            <div class="portfolio-description">
              <h2>{{ project_info.project_name }}</h2>
              <p>
                {{ project_info.intro }}
              </p>
              <p >
                {{ project_info.project_description|linebreaks }}
              </p>
             
            </div>
          </div>

          <div class="col-lg-3" data-aos="fade-up" data-aos-delay="100">
            <div class="portfolio-info">
              <h3>Project information</h3>
              <ul>
                <li><strong>Category</strong>  {{ project_info.category_type }}</li>
                <!-- <li><strong>Client</strong> ASU Company</li> -->
                <li><strong>Project Stack</strong>
                   {{ project_info.stack|linebreaks }}
               </li>
               <li><strong>Status</strong>{{ project_info.status }}</li>
                <!-- <li><strong>Project URL</strong> <a href="#">www.example.com</a></li> -->
                <li><a href="#" class="btn-visit align-self-start">Visit Website</a></li>
              </ul>
            </div>
          </div>

        </div>

      </div>

    </section><!-- /Portfolio Details Section -->

  </main>

  {% include 'footer.html' %}

  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  {% include 'JSimport.html' %}

</body>

</html>

Portfolio/templates/footer.html
<footer id="footer" class="footer position-relative light-background">
    <div class="container">
      
      <div class="container">
        <div class="credits">
          Modified  by <a href="https://www.github.com/surajgiri974">Suraj Giri</a>
        </div>
      </div>
    </div>
  </footer>

Portfolio/templates/imports.html
{% load static %}

<link href="{% static 'assets/img/faviicon.png' %}" rel="icon" type="image/png" >
  <link href="{% static 'assets/img/apple-touch.png' %}" rel="apple-touch-icon" type="image/png" >
  
  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">

Portfolio/templates/navigation.html
<header id="header" class="header d-flex flex-column justify-content-center">

    <i class="header-toggle d-xl-none bi bi-list"></i>

    <nav id="navmenu" class="navmenu">
      <ul>
        <li><a href="{% url 'portfolio:home' %}#home" class="active"><i class="bi bi-house navicon"></i><span>Home</span></a></li>
        <li><a href="{% url 'portfolio:home' %}#about"><i class="bi bi-person navicon"></i><span>About</span></a></li>
        <li><a href="{% url 'portfolio:home' %}#skills"><i class="bi bi-bar-chart-line navicon"></i><span>Skills</span></a></li>
        <li><a href="{% url 'portfolio:home' %}#resume"><i class="bi bi-file-earmark-text navicon"></i><span>Resume</span></a></li>
        <li><a href="{% url 'portfolio:home' %}#portfolio"><i class="bi bi-images navicon"></i><span>Portfolio</span></a></li>
        <li><a href="{% url 'portfolio:home' %}#contact"><i class="bi bi-envelope navicon"></i><span>Contact</span></a></li>
      </ul>
    </nav>

  </header>